services:
  database:
    container_name: database
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=cltrr
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  server:
    container_name: server
    build: 
      context: ..
      dockerfile: ./build/package/server.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://cltrr:passw0rd@database:5432/cltrr
  client:
    container_name: client
    build: 
      context: ../web
      dockerfile: ../build/package/client.Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server
volumes:
  db:
    driver: local